package project_uas_sem2;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.internal.vm.PostVMInitHook.run;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ytcraft
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    
    String dat = "E:\\2. SEMESTER 2\\1. ALGORITMA & PEMROGRAMAN\\1. PROJET\\TUGAS_AKHIR\\isi.txt";
    DefaultTableModel dataModel;
    List list;
    private AnakAnak a = new AnakAnak();
    private Bayi b = new Bayi();
    private IbuHamil c = new IbuHamil();
    private Pria d = new Pria();
    private Wanita e = new Wanita();
    
    private boolean kuy = true;
    public HOME() {
        initComponents();
        dataModel = (DefaultTableModel) table.getModel();
        list = new ArrayList<>();
        table.setAutoCreateColumnsFromModel(true);
        U.setEnabled(false);
        T.setEnabled(false);
        BB.setEnabled(false);
        BBI.setEnabled(false);
    }
    
    void Buat(){
          String JenisKelamin = null;
        if (nama.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Silahkan isi form nama terlebih dahulu!!!");
        }else {
            if(this.JenisKelamin.getSelectedItem()=="Kategori"){
                JOptionPane.showMessageDialog(null,"silahkan pilih Kategori terlebih dahulu!!!");
            }else{
            if(this.JenisKelamin.getSelectedItem()=="Pria"){
                Pria a = new Pria();
                a.setVisible(true);
                a.pack();
                a.setLocationRelativeTo(null);
                a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                Pria.nama1.setText(nama.getText());
            }else if(this.JenisKelamin.getSelectedItem()=="Wanita"){
                Wanita a = new Wanita();
                a.setVisible(true);
                a.pack();
                a.setLocationRelativeTo(null);
                a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                Wanita.nama1.setText(nama.getText());
            }else if(this.JenisKelamin.getSelectedItem()=="Anak-anak"){
                AnakAnak a = new AnakAnak();
                a.setVisible(true);
                a.pack();
                a.setLocationRelativeTo(null);
                a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                AnakAnak.nama1.setText(nama.getText());
            }else if(this.JenisKelamin.getSelectedItem()=="Ibu Hamil"){
                IbuHamil a = new IbuHamil();
                a.setVisible(true);
                a.pack();
                a.setLocationRelativeTo(null);
                a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                IbuHamil.nama1.setText(nama.getText());
            }else if(this.JenisKelamin.getSelectedItem()=="Bayi"){
                Bayi a = new Bayi();
                a.setVisible(true);
                a.pack();
                a.setLocationRelativeTo(null);
                a.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                Bayi.nama1.setText(nama.getText());
            }
        }
        }
    }
    
    void loadData(){
      //   if(kuy){
        
     //   }else{
            Buat();
      //  }
        
    }
        void muncul(){
        dataModel.setRowCount(0);
        table.setModel(dataModel);
        String sem = "";
        try {
            Scanner A = new Scanner(new File(dat));
            while(A.hasNext()){
                sem += A.nextLine();
            }
            String pisah[] = sem.split("|");
            for (int i = 0; i < pisah.length; i++) {
                String pisah_kolom[]=pisah[i].split("-");
                for (int j = 0; j < pisah_kolom.length; j++) {
                    list.add(pisah_kolom[j]);
                }
                dataModel.addRow(list.toArray());
                list.clear();
            }
        } catch (Exception e) {
        }
    }
        
        
        private void tampil() {
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        pilih = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        hapus = new javax.swing.JToggleButton();
        JenisKelamin = new javax.swing.JComboBox<>();
        ubahData = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        U = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        T = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BBI = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ideal Weight Body");

        jLabel3.setText("Nama         :");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        pilih.setText("Pilih");
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Jenis Kelamin", "Umur", "Tinggi", "Berat  Badan", "Berat Badan Ideal"
            }
        ));
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(1);
            table.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        hapus.setText("Hapus Data");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        JenisKelamin.setEditable(true);
        JenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kategori", "Pria", "Wanita", "Ibu Hamil", "Anak-anak", "Bayi" }));
        JenisKelamin.setAutoscrolls(true);

        ubahData.setText("Ubah Data");
        ubahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahDataActionPerformed(evt);
            }
        });

        jLabel2.setText("Umur");

        jLabel4.setText("Tinggi");

        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });

        jLabel5.setText("Berat Badan");

        jLabel6.setText("BBI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BBI, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(U))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(ubahData, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BB, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(U, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pilih)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hapus)
                        .addComponent(ubahData)
                        .addComponent(BBI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
Buat();  
    }//GEN-LAST:event_pilihActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int dm = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus Data ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if(dm == 0){
          DefaultTableModel hapus = (DefaultTableModel)table.getModel();
        try{
           int Selected = table.getSelectedRow();
           hapus.removeRow(Selected);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }  
        }else{
            
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void ubahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahDataActionPerformed
        int dm = JOptionPane.showConfirmDialog(null, "Yakin ingin mengubah data ?", "Ubah Data", JOptionPane.YES_NO_OPTION);
        if(dm == 0){
          DefaultTableModel hapus = (DefaultTableModel)table.getModel();
        try{
           int Selected = table.getSelectedRow();
           hapus.removeRow(Selected);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            Buat();
        }  
        }else{
            
        }
        Buat();
    }//GEN-LAST:event_ubahDataActionPerformed

    private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TActionPerformed

       void ubahTambah(){
               int ubah =table.getSelectedRowCount();
        
         if (ubah > 0) {
            
            int pil;
            pil = JOptionPane.NO_OPTION;
            pil = JOptionPane.showConfirmDialog(rootPane, "Apakah Anda Ingin Mengubah?", "Informasi", 
                                                                       JOptionPane.YES_NO_OPTION);
            if (pil == JOptionPane.YES_OPTION) {
                int row = table.getSelectedRow();
                
                nama.setText(table.getValueAt(row, 0).toString());
                JenisKelamin.setSelectedItem(table.getValueAt(row, 1));
                U.setText(table.getValueAt(row, 2).toString());
                T.setText(table.getValueAt(row, 3).toString());
                BB.setText(table.getValueAt(row, 4).toString());
                BBI.setText(table.getValueAt(row, 5).toString());
            }
            kuy =false;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Silahkan Masukkan Data Dahulu!");
        }
    }
       
    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed
    public static void addrow(Object [] Addrow) {
        DefaultTableModel tb = (DefaultTableModel)table.getModel();
        tb.addRow(Addrow);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField BB;
    public static javax.swing.JTextField BBI;
    private javax.swing.JComboBox<String> JenisKelamin;
    public static javax.swing.JTextField T;
    public static javax.swing.JTextField U;
    private javax.swing.JToggleButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextField nama;
    private javax.swing.JButton pilih;
    public static javax.swing.JTable table;
    private javax.swing.JButton ubahData;
    // End of variables declaration//GEN-END:variables

    private int ubahData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
